# Numpy Operations

In [175]:
import numpy


In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [2]:
import numpy as np

In [17]:
a = np.array([1,2,3,"a","b","c"])
print(a)

['1' '2' '3' 'a' 'b' 'c']


In [19]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
b.shape # Rows x Columns


(2, 3)

In [9]:
a.shape

(3,)

In [22]:
b.dtype, a.dtype

(dtype('int32'), dtype('<U11'))

In [11]:
b.ndim

2

In [13]:
print(type(a), type(b))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [15]:
np.arange(10) # no loop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Efficiency of numpy

1. Iteration in a list

In [18]:
c = range(10000)
%timeit [i**3 for i in c]

3.7 ms ± 72.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
c_numpy = np.arange(10000)
%timeit [c_numpy**3]

28.6 µs ± 1.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


2. computation among lists



In [27]:
l1 = range(1000)
l2 = [i**2 for i in range(1000)]

In [35]:
%timeit list(map(lambda x,y: x*y, l1,l2))

166 µs ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
a1 = np.array(l1)
a2 = np.array(l2)

In [37]:
%timeit a1*a2 #no for loop reqd.

2.3 µs ± 106 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
np.arange(2,10), np.arange(2,10,3)
#np.arange(a,b,c) = > a is starting index, b is ending index-1, c is jump

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([2, 5, 8]))

In [43]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.full((2,3),2) #no np.twos and so on

array([[2, 2, 2],
       [2, 2, 2]])

In [45]:
np.eye(3)  #identity matrix of input size

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
 np.full((3,3),4.2)

array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]])

In [49]:
np.full((3,3),4.2, dtype = np.int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [50]:
np.diag([1,2,3,4]) #custom diagonal matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [52]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [59]:
np.tile(v,3) , np.tile(v,(3,1)) , np.tile(v,(3,2))  #scope of imagination

(array([1, 2, 3, 1, 2, 3, 1, 2, 3]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]))

In [65]:
np.random.random()

0.7354810519088358

In [62]:
50 * np.random.random() + 2

34.81954814680398

In [66]:
np.random.random([3,3])

array([[0.47361942, 0.7822266 , 0.57416441],
       [0.45452683, 0.80945634, 0.70192777],
       [0.37848841, 0.24798381, 0.80962921]])

In [71]:
 a = np.linspace(1,50,100)

In [72]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [74]:
a.itemsize

8

In [78]:
b = np.arange(18).reshape(2,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [79]:
b.shape # b is a 3-D array

(2, 3, 3)

In [80]:
np.arange(18).reshape(2,3,-1) # -1 is for auto calculation of 3rd dimension

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [89]:
a = np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [83]:
a[0], a[3]

(2, 8)

In [84]:
a[[2,4,6]]

array([ 6, 10, 14])

In [85]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [86]:
a[0::2]

array([ 2,  6, 10, 14])

In [92]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
a[2,2]

9

In [95]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [96]:
a[(a>2)&(a<5)] 

array([3, 4])

In [101]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
b[0] = 11
b


array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [105]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [106]:
# change in b also changes a => np array a and b have same references.

In [107]:
np.shares_memory(a,b)

True

In [110]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
b[0] = 11
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [113]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.shares_memory(a,b)

False

In [115]:
# if we don't wanna have same references use copy instead of directly assigning

In [117]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
a.T # transpose of a matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
b = np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [121]:
a == b

array([[False, False, False],
       [False, False, False]])

In [122]:
#stacking a and b

In [125]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [126]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [127]:
a = np.arange(1,10)

In [128]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [130]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [131]:
np.sum(a) # sum all elements of a

45

In [132]:
np.median(a)

5.0

In [133]:
np.std(a)

2.581988897471611

In [137]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.linalg.det(a) # determinant of a

6.66133814775094e-16

In [141]:
np.linalg.inv(a) # inverse of a

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [143]:
np.linalg.eig(a) # eighen values of a

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [146]:
b = a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [145]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [152]:
a = np.array([1,1,0])
b = np.array([1,0,1])

In [153]:
a,b

(array([1, 1, 0]), array([1, 0, 1]))

In [154]:
np.logical_or(a,b)

array([ True,  True,  True])

In [155]:
np.logical_and(a,b)

array([ True, False, False])

In [156]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [159]:
np.sum(a) 

10

In [161]:
a.sum(axis = 0) # columnwise sum

array([4, 6])

In [162]:
a.sum(axis = 1) # rowwise sum

array([3, 7])

In [163]:
a.max() # max value of a

4

In [164]:
a.argmax() #index of max value

3

In [165]:
a.shape

(2, 2)

In [170]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
a.shape

(9,)

In [172]:
a[:,np.newaxis].shape #converting data to different dimension

(9, 1)

In [173]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Pandas Operations
Built on top of numpy <br>
used for data manipulations and visualisation of data <br>
2 main data structures available - series and dataframe(mostly used) 


##  Pandas Series

In [176]:
import pandas as pd


In [182]:
a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

Index --  value 

In [180]:
type(a)

pandas.core.series.Series

In [183]:
a[2]

3

In [184]:
a[3:]

3    4
4    5
dtype: int64

In [185]:
a = pd.Series(["a","b","c"])
a

0    a
1    b
2    c
dtype: object

String is represented as object in pandas series

In [194]:
a = pd.date_range(start = "28-02-2021", end = "14-03-2021")
a

DatetimeIndex(['2021-02-28', '2021-03-01', '2021-03-02', '2021-03-03',
               '2021-03-04', '2021-03-05', '2021-03-06', '2021-03-07',
               '2021-03-08', '2021-03-09', '2021-03-10', '2021-03-11',
               '2021-03-12', '2021-03-13', '2021-03-14'],
              dtype='datetime64[ns]', freq='D')

In [195]:
type(a) # a is time series.

pandas.core.indexes.datetimes.DatetimeIndex

## Pandas Dataframes

### 1. using numpy and list


In [196]:
import numpy as np

In [206]:
temp = np.random.randint(low = 1, high = 10, size = 20)
temp

array([2, 3, 8, 6, 5, 7, 5, 1, 5, 6, 6, 4, 7, 8, 8, 5, 3, 3, 4, 8])

In [199]:
name = np.random.choice(["shaleen","sumit","ujju","ajit"],20)
name

array(['shaleen', 'ujju', 'sumit', 'sumit', 'sumit', 'ajit', 'sumit',
       'ajit', 'ujju', 'shaleen', 'sumit', 'sumit', 'sumit', 'ajit',
       'ujju', 'ujju', 'shaleen', 'sumit', 'shaleen', 'shaleen'],
      dtype='<U7')

In [204]:
random = np.random.choice([28,30,33,3],20)
random

array([33, 28, 33,  3,  3, 30, 30, 33, 30,  3, 28, 30, 28, 33,  3, 33, 33,
       28, 30, 28])

In [207]:
a = list(zip(temp, name, random))
a

[(2, 'shaleen', 33),
 (3, 'ujju', 28),
 (8, 'sumit', 33),
 (6, 'sumit', 3),
 (5, 'sumit', 3),
 (7, 'ajit', 30),
 (5, 'sumit', 30),
 (1, 'ajit', 33),
 (5, 'ujju', 30),
 (6, 'shaleen', 3),
 (6, 'sumit', 28),
 (4, 'sumit', 30),
 (7, 'sumit', 28),
 (8, 'ajit', 33),
 (8, 'ujju', 3),
 (5, 'ujju', 33),
 (3, 'shaleen', 33),
 (3, 'sumit', 28),
 (4, 'shaleen', 30),
 (8, 'shaleen', 28)]

In [208]:
type(a)

list

In [210]:
df = pd.DataFrame(data = a, columns = ["Temp","Name","Roll no."])
df

Temp     Name  Roll no.
0      2  shaleen        33
1      3     ujju        28
2      8    sumit        33
3      6    sumit         3
4      5    sumit         3
5      7     ajit        30
6      5    sumit        30
7      1     ajit        33
8      5     ujju        30
9      6  shaleen         3
10     6    sumit        28
11     4    sumit        30
12     7    sumit        28
13     8     ajit        33
14     8     ujju         3
15     5     ujju        33
16     3  shaleen        33
17     3    sumit        28
18     4  shaleen        30
19     8  shaleen        28

In [211]:
type(df)

pandas.core.frame.DataFrame

### 2. using dictionary

In [214]:
df = pd.DataFrame({"temp":temp, "name":name, "roll":random})

In [215]:
df

temp     name  roll
0      2  shaleen    33
1      3     ujju    28
2      8    sumit    33
3      6    sumit     3
4      5    sumit     3
5      7     ajit    30
6      5    sumit    30
7      1     ajit    33
8      5     ujju    30
9      6  shaleen     3
10     6    sumit    28
11     4    sumit    30
12     7    sumit    28
13     8     ajit    33
14     8     ujju     3
15     5     ujju    33
16     3  shaleen    33
17     3    sumit    28
18     4  shaleen    30
19     8  shaleen    28

In [216]:
type(df)

pandas.core.frame.DataFrame

### operations on dataframe

In [217]:
df.head() # shows first 5 values of df

temp     name  roll
0     2  shaleen    33
1     3     ujju    28
2     8    sumit    33
3     6    sumit     3
4     5    sumit     3

In [218]:
df.tail() # last 5

temp     name  roll
15     5     ujju    33
16     3  shaleen    33
17     3    sumit    28
18     4  shaleen    30
19     8  shaleen    28

In [219]:
df.shape

(20, 3)

In [221]:
df.columns

Index(['temp', 'name', 'roll'], dtype='object')

In [222]:
df.name

0     shaleen
1        ujju
2       sumit
3       sumit
4       sumit
5        ajit
6       sumit
7        ajit
8        ujju
9     shaleen
10      sumit
11      sumit
12      sumit
13       ajit
14       ujju
15       ujju
16    shaleen
17      sumit
18    shaleen
19    shaleen
Name: name, dtype: object

In [223]:
df["name"]

0     shaleen
1        ujju
2       sumit
3       sumit
4       sumit
5        ajit
6       sumit
7        ajit
8        ujju
9     shaleen
10      sumit
11      sumit
12      sumit
13       ajit
14       ujju
15       ujju
16    shaleen
17      sumit
18    shaleen
19    shaleen
Name: name, dtype: object

In [226]:
df["temp"].describe()

count    20.000000
mean      5.200000
std       2.117595
min       1.000000
25%       3.750000
50%       5.000000
75%       7.000000
max       8.000000
Name: temp, dtype: float64

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   temp    20 non-null     int32 
 1   name    20 non-null     object
 2   roll    20 non-null     int32 
dtypes: int32(2), object(1)
memory usage: 448.0+ bytes


In [228]:
df.values # returns df as array

array([[2, 'shaleen', 33],
       [3, 'ujju', 28],
       [8, 'sumit', 33],
       [6, 'sumit', 3],
       [5, 'sumit', 3],
       [7, 'ajit', 30],
       [5, 'sumit', 30],
       [1, 'ajit', 33],
       [5, 'ujju', 30],
       [6, 'shaleen', 3],
       [6, 'sumit', 28],
       [4, 'sumit', 30],
       [7, 'sumit', 28],
       [8, 'ajit', 33],
       [8, 'ujju', 3],
       [5, 'ujju', 33],
       [3, 'shaleen', 33],
       [3, 'sumit', 28],
       [4, 'shaleen', 30],
       [8, 'shaleen', 28]], dtype=object)

In [229]:
df

temp     name  roll
0      2  shaleen    33
1      3     ujju    28
2      8    sumit    33
3      6    sumit     3
4      5    sumit     3
5      7     ajit    30
6      5    sumit    30
7      1     ajit    33
8      5     ujju    30
9      6  shaleen     3
10     6    sumit    28
11     4    sumit    30
12     7    sumit    28
13     8     ajit    33
14     8     ujju     3
15     5     ujju    33
16     3  shaleen    33
17     3    sumit    28
18     4  shaleen    30
19     8  shaleen    28

In [230]:
df.set_index("temp") #changing index

name  roll
temp               
2     shaleen    33
3        ujju    28
8       sumit    33
6       sumit     3
5       sumit     3
7        ajit    30
5       sumit    30
1        ajit    33
5        ujju    30
6     shaleen     3
6       sumit    28
4       sumit    30
7       sumit    28
8        ajit    33
8        ujju     3
5        ujju    33
3     shaleen    33
3       sumit    28
4     shaleen    30
8     shaleen    28

In [231]:
df # again back to normal

temp     name  roll
0      2  shaleen    33
1      3     ujju    28
2      8    sumit    33
3      6    sumit     3
4      5    sumit     3
5      7     ajit    30
6      5    sumit    30
7      1     ajit    33
8      5     ujju    30
9      6  shaleen     3
10     6    sumit    28
11     4    sumit    30
12     7    sumit    28
13     8     ajit    33
14     8     ujju     3
15     5     ujju    33
16     3  shaleen    33
17     3    sumit    28
18     4  shaleen    30
19     8  shaleen    28

In [233]:
df.set_index("temp", inplace = True) # permanently changes index

In [234]:
df

name  roll
temp               
2     shaleen    33
3        ujju    28
8       sumit    33
6       sumit     3
5       sumit     3
7        ajit    30
5       sumit    30
1        ajit    33
5        ujju    30
6     shaleen     3
6       sumit    28
4       sumit    30
7       sumit    28
8        ajit    33
8        ujju     3
5        ujju    33
3     shaleen    33
3       sumit    28
4     shaleen    30
8     shaleen    28

In [238]:
df.sort_index(axis = 0, ascending = True) #sorting index

name  roll
temp               
1        ajit    33
2     shaleen    33
3        ujju    28
3       sumit    28
3     shaleen    33
4     shaleen    30
4       sumit    30
5       sumit     3
5        ujju    33
5       sumit    30
5        ujju    30
6     shaleen     3
6       sumit     3
6       sumit    28
7       sumit    28
7        ajit    30
8        ajit    33
8        ujju     3
8       sumit    33
8     shaleen    28

In [240]:
df.sort_values("name") # sorting based on name column

name  roll
temp               
8        ajit    33
1        ajit    33
7        ajit    30
2     shaleen    33
3     shaleen    33
4     shaleen    30
6     shaleen     3
8     shaleen    28
5       sumit     3
6       sumit     3
6       sumit    28
4       sumit    30
7       sumit    28
8       sumit    33
3       sumit    28
5       sumit    30
5        ujju    30
8        ujju     3
5        ujju    33
3        ujju    28

In [242]:
df.drop(["name"], axis = 1) #delete name column, not permanent unless inlace is set true

roll
temp      
2       33
3       28
8       33
6        3
5        3
7       30
5       30
1       33
5       30
6        3
6       28
4       30
7       28
8       33
8        3
5       33
3       33
3       28
4       30
8       28

In [243]:
df.head() #since not a permanent change

name  roll
temp               
2     shaleen    33
3        ujju    28
8       sumit    33
6       sumit     3
5       sumit     3

### loc and iloc

In [245]:
df.iloc[[0,1]] # 0th index row and 1st index row

name  roll
temp               
2     shaleen    33
3        ujju    28

In [256]:
df.iloc[1:5,1] # it means row from 1 to 4 and keep only column 1

temp
3    28
8    33
6     3
5     3
Name: roll, dtype: int32

In [258]:
df.iloc[1:5,0] # it means row from 1 to 4 and keep only column 0

temp
3     ujju
8    sumit
6    sumit
5    sumit
Name: name, dtype: object

In [260]:
# temp columns is index column so it will not be counted in columns, 
# 0th column will be name column and 1st column is roll

In [263]:
df.iloc[0,:] # as per actual index, technically index of 0th row is 2(as per temp column which in index column)

name    shaleen
roll         33
Name: 2, dtype: object

In [264]:
df.loc[2,:]

name    shaleen
roll         33
Name: 2, dtype: object

In [266]:
# => iloc works with actual index and loc works with technical or set index

In [270]:
df.loc[df.roll > 30]

name  roll
temp               
2     shaleen    33
8       sumit    33
1        ajit    33
8        ajit    33
5        ujju    33
3     shaleen    33

In [271]:
df.loc[df.roll == 28]

name  roll
temp               
3        ujju    28
6       sumit    28
7       sumit    28
3       sumit    28
8     shaleen    28

In [283]:
df.loc[(df.name == "sumit") & (df.roll == 30)]

name  roll
temp             
5     sumit    30
4     sumit    30

### Merging DataFrames

In [291]:
df1 = pd.DataFrame([["a",1],["b",2],["e",5]], columns = ["coll", "number"])
df2 = pd.DataFrame([["c",3,"lion"],["d",4,"tiger"]], columns = ["letter", "number", "animal"])

In [292]:
df1

coll  number
0    a       1
1    b       2
2    e       5

In [287]:
df2

letter  number animal
0      c       3   lion
1      d       4  tiger

In [293]:
pd.concat([df1,df2], axis = 0) # concat row wise based on common column - number

coll  number letter animal
0    a       1    NaN    NaN
1    b       2    NaN    NaN
2    e       5    NaN    NaN
0  NaN       3      c   lion
1  NaN       4      d  tiger

In [294]:
pd.concat([df1,df2], axis = 0, ignore_index = True)

coll  number letter animal
0    a       1    NaN    NaN
1    b       2    NaN    NaN
2    e       5    NaN    NaN
3  NaN       3      c   lion
4  NaN       4      d  tiger

In [295]:
pd.concat([df1,df2], axis = 1) # concat column wise

coll  number letter  number animal
0    a       1      c     3.0   lion
1    b       2      d     4.0  tiger
2    e       5    NaN     NaN    NaN

In [297]:
d1 = pd.DataFrame({
    "city" : ["lucknow", "kanpur", "agra", "delhi"],
    "temprature" : [32,45,30,40]
})
d1


city  temprature
0  lucknow          32
1   kanpur          45
2     agra          30
3    delhi          40

In [298]:
d2 = pd.DataFrame({
    "city" : ["delhi", "lucknow", "kanpur"],
    "humidity" : [68,65,75]
})
d2

city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75

In [301]:
d3 = pd.merge(d1,d2,on = "city")
d3

city  temprature  humidity
0  lucknow          32        65
1   kanpur          45        75
2    delhi          40        68

In [302]:
pd.merge(d1,d2,on = "city", how = "outer")  #outer join, can also try some another join

city  temprature  humidity
0  lucknow          32      65.0
1   kanpur          45      75.0
2     agra          30       NaN
3    delhi          40      68.0

### Reading from CSV file
CSV : Comma Separated File

In [308]:
df1 = pd.read_csv("weather_data.csv")
df1

day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny
6  01-07-2017           33          6   Rain

In [343]:
df1.to_excel("df_xl.xlsx", sheet_name = "weather", index = False) #created a excel from csv

In [ ]:
# if index = false is not there, one extra column of index will be created

In [341]:
df2 = pd.read_excel("df_xl.xlsx")

In [342]:
df2

day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny
6  01-07-2017           33          6   Rain

In [368]:
# df2.to_csv("file.csv", index = false)  => excel to csv

### groupby and applying functions to dataframe

In [345]:
df_group = df2.groupby("event")

In [346]:
df_group

In [347]:
for events in df_group:
    print(events)

('Rain',           day  temperature  windspeed event
0  01-01-2017           32          6  Rain
4  01-05-2017           32          4  Rain
6  01-07-2017           33          6  Rain)
('Snow',           day  temperature  windspeed event
2  01-03-2017           28          2  Snow
3  01-04-2017           24          7  Snow)
('Sunny',           day  temperature  windspeed  event
1  01-02-2017           35          7  Sunny
5  01-06-2017           31          2  Sunny)


In [349]:
df_group.get_group("Rain")

day  temperature  windspeed event
0  01-01-2017           32          6  Rain
4  01-05-2017           32          4  Rain
6  01-07-2017           33          6  Rain

In [350]:
df_group.describe()

temperature                                                     \
            count       mean       std   min   25%   50%   75%   max   
event                                                                  
Rain          3.0  32.333333  0.577350  32.0  32.0  32.0  32.5  33.0   
Snow          2.0  26.000000  2.828427  24.0  25.0  26.0  27.0  28.0   
Sunny         2.0  33.000000  2.828427  31.0  32.0  33.0  34.0  35.0   

      windspeed                                                 
          count      mean       std  min   25%  50%   75%  max  
event                                                           
Rain        3.0  5.333333  1.154701  4.0  5.00  6.0  6.00  6.0  
Snow        2.0  4.500000  3.535534  2.0  3.25  4.5  5.75  7.0  
Sunny       2.0  4.500000  3.535534  2.0  3.25  4.5  5.75  7.0

In [351]:
def hot_temp(x):
    return x>30

In [362]:
df2["Hot Temp"] = df2["temperature"].apply(hot_temp)

In [354]:
df2

day  temperature  windspeed  event  Hot Temp
0  01-01-2017           32          6   Rain      True
1  01-02-2017           35          7  Sunny      True
2  01-03-2017           28          2   Snow     False
3  01-04-2017           24          7   Snow     False
4  01-05-2017           32          4   Rain      True
5  01-06-2017           31          2  Sunny      True
6  01-07-2017           33          6   Rain      True

In [366]:
df2["hot_temprature"] = df2["temperature"].apply(lambda x: x>30)

In [367]:
df2

day  temperature  windspeed  event  Hot Temp  hot_temprature  \
0  01-01-2017           32          6   Rain      True            True   
1  01-02-2017           35          7  Sunny      True            True   
2  01-03-2017           28          2   Snow     False           False   
3  01-04-2017           24          7   Snow     False           False   
4  01-05-2017           32          4   Rain      True            True   
5  01-06-2017           31          2  Sunny      True            True   
6  01-07-2017           33          6   Rain      True            True   

   Hot_temp  
0      True  
1      True  
2     False  
3     False  
4      True  
5      True  
6      True

### pivot table

In [380]:
df2.drop(["hot_temprature"], axis = 1, inplace = True)

In [381]:
df2

day  temperature  windspeed  event  Hot Temp
0  01-01-2017           32          6   Rain      True
1  01-02-2017           35          7  Sunny      True
2  01-03-2017           28          2   Snow     False
3  01-04-2017           24          7   Snow     False
4  01-05-2017           32          4   Rain      True
5  01-06-2017           31          2  Sunny      True
6  01-07-2017           33          6   Rain      True

In [386]:
df2.pivot_table(values = "temperature", index = "event", aggfunc = "count")


temperature
event             
Rain             3
Snow             2
Sunny            2

In [387]:
df2.pivot_table(values = "temperature", index = "event", aggfunc = "mean")

temperature
event             
Rain     32.333333
Snow     26.000000
Sunny    33.000000

In [389]:
df2.pivot_table(columns = "temperature")

temperature     24     28    31    32    33    35
Hot Temp     False  False  True  True  True  True
windspeed        7      2     2     5     6     7

## for more help use help function

In [390]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=False) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.
    
    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.
    
    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        li